/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hu.ingatlan.verseny.swing;

/**
 *
 * @author csaba
 */
public class AblakTesztGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AblakTesztGUI.class.getName());

    /**
     * Creates new form Ablak
     */
    public AblakTesztGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jKilepesButton = new javax.swing.JButton();
        jKeresesButton = new javax.swing.JButton();
        jTorlesAListabolsButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jBecsultErtekTextPanel = new javax.swing.JTextPane();
        jHelyrajziSzamLabel = new javax.swing.JLabel();
        jBecsultErtekUpdateListabolsButton1 = new javax.swing.JButton();
        jBecsultErtekLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jHelyraziSzamTextPanel1 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jIngatlanList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jKilepesButton.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jKilepesButton.setForeground(new java.awt.Color(255, 0, 51));
        jKilepesButton.setText("Kilépés");
        jKilepesButton.setToolTipText("Ha a gombra kattintasz kilép az alkalmazásból");
        jKilepesButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jKilepesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKilepesButtonActionPerformed(evt);
            }
        });

        jKeresesButton.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jKeresesButton.setText("Keresés");
        jKeresesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKeresesButtonActionPerformed(evt);
            }
        });

        jTorlesAListabolsButton.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jTorlesAListabolsButton.setText("Törlés a listából");
        jTorlesAListabolsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTorlesAListabolsButtonActionPerformed(evt);
            }
        });

        jBecsultErtekTextPanel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jScrollPane2.setViewportView(jBecsultErtekTextPanel);

        jHelyrajziSzamLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jHelyrajziSzamLabel.setText("Helyrajzi szám:");

        jBecsultErtekUpdateListabolsButton1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jBecsultErtekUpdateListabolsButton1.setText("Becsült érték frissítése");
        jBecsultErtekUpdateListabolsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBecsultErtekUpdateListabolsButton1ActionPerformed(evt);
            }
        });

        jBecsultErtekLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBecsultErtekLabel.setText("Becsült érték:");

        jHelyraziSzamTextPanel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jScrollPane3.setViewportView(jHelyraziSzamTextPanel1);

        jIngatlanList.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jScrollPane4.setViewportView(jIngatlanList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jHelyrajziSzamLabel)
                            .addComponent(jBecsultErtekLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBecsultErtekUpdateListabolsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jKeresesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(jKilepesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTorlesAListabolsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jHelyrajziSzamLabel)
                    .addComponent(jKeresesButton)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBecsultErtekUpdateListabolsButton1)
                    .addComponent(jBecsultErtekLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jTorlesAListabolsButton)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(jKilepesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jKilepesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKilepesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKilepesButtonActionPerformed

    private void jKeresesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKeresesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jKeresesButtonActionPerformed

    private void jTorlesAListabolsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTorlesAListabolsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTorlesAListabolsButtonActionPerformed

    private void jBecsultErtekUpdateListabolsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBecsultErtekUpdateListabolsButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBecsultErtekUpdateListabolsButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AblakTesztGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBecsultErtekLabel;
    private javax.swing.JTextPane jBecsultErtekTextPanel;
    private javax.swing.JButton jBecsultErtekUpdateListabolsButton1;
    private javax.swing.JLabel jHelyrajziSzamLabel;
    private javax.swing.JTextPane jHelyraziSzamTextPanel1;
    private javax.swing.JList<String> jIngatlanList;
    private javax.swing.JButton jKeresesButton;
    private javax.swing.JButton jKilepesButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jTorlesAListabolsButton;
    // End of variables declaration//GEN-END:variables
}
